name: Live Voting System

services:
  backend:
    container_name: backend-service
    build:
      context: backend
    ports:
      - 8080:8080
    environment:
      - MAX_OPEN_CONN=${MAX_OPEN_CONN}
      - MAX_IDLE_CONN=${MAX_IDLE_CONN}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    networks:
      - logging-network
      - db_network
    secrets:
      - db_password
    depends_on:
      - elasticsearch
      - postgres

  postgres:
    container_name: postgres-db-service
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - "5432:5432"
    secrets:
      - db_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - logging-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    networks:
      - logging-network
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - logging-network
    depends_on:
      - elasticsearch

networks:
  logging-network:
  db_network:

secrets:
  db_password:
    file: ./.secrets/db_password.txt

volumes:
  postgres_data:
